In [1]:
# Don't change the style of these imports.
# They must be imported this way for parallelization
# to work correctly.
import lxml.html
import ujson
import gzip
import csv
import datetime

In [2]:
from pdb import set_trace as debug
from IPython.parallel import Client,require
from collections import Counter
from pandas.io.parsers import read_csv

In [3]:
#--> RAW_FILE_DIR with the directory that contains google_play__main.json.gz
#--> OUT_DIR with the directory of where you want the processed files to go
#--> DEBUG whether to print out created CSV files or not
#--> COMPRESS_LEVEL gzip compression level. warning: severely impacts runtime.
#--> LINE_LIMIT how many lines to iterate through in the raw file. For debugging.
DUMP_DATE = '2015_03_21_23_12'
RAW_FILE_DIR = '/Users/kushagrasharma/Coding/data'
OUT_DIR = '/Users/kushagrasharma/Coding/data/out'
DEBUG = 1
COMPRESS_LEVEL = 1
LINE_LIMIT = -1 # -1 means run for the entire file
PARALLEL = 0

In [4]:
# Don't change these!
RAW_FILE_IPHONE = '{}/test_appannie__iphone.json.gz'.format(RAW_FILE_DIR)
RAW_FILE_IPAD = '{}/test_appannie__ipad.json.gz'.format(RAW_FILE_DIR)
RAW_FILE_GOOGLE = '{}/test_appannie__google.json.gz'.format(RAW_FILE_DIR)
RAW_FILE_HISTORICALRANKINGS = '{}/appannie__historical_rankings.json.gz'.format(RAW_FILE_DIR)
RAW_FILE_HISTORICALEVENTS = '{}/appannie__historical_events.json.gz'.format(RAW_FILE_DIR)

OUT_BASE = OUT_DIR+'/{}__'+DUMP_DATE+'.csv.gz'

In [5]:
# ! zcat "$RAW_FILE_IPHONE" | head -n1
# ! zcat "$RAW_FILE_IPAD" | head -n1
# ! zcat "$RAW_FILE_GOOGLE" | head -n1

In [6]:
def iter_json_gzip(filename,LINE_LIMIT=LINE_LIMIT,no_verify_appid_time=1):
    with gzip.open(filename,'rt') as file_iter:
        c = 0
        for line in file_iter:
            c +=1
            if c > LINE_LIMIT and LINE_LIMIT>0:
                break
            if isinstance(line,str):
                if len(line)>0:        
                    out = ujson.loads(line)
                    if isinstance(out,dict):
                        if 'app_id' in out and 'timestamp' in out \
                        or no_verify_appid_time:
                            yield out

In [7]:
if PARALLEL:
    ipython_parallel = Client()
    print("{} active computing engines".format(len(ipython_parallel.ids)))

    lbv = ipython_parallel.load_balanced_view()

    map = lambda f,itertable:lbv.map(f,itertable,\
    block =False,\
    ordered =False)

    @require('socket')
    def host(dummy):
        return socket.gethostname()
    
    nodes = list(lbv.map(host,ipython_parallel.ids))
    nodes = [int(x.split('equity')[1].split(".")[0]) for x in nodes]
    nodes = nodes

    print(sorted(list(Counter(nodes).items())))

# RANKINGS_IPHONE

In [8]:
@require(iter_json_gzip,'ujson','gzip','csv','lxml.html')
def RANKINGS_IPHONE(file_in,out_base,compress=1):
    headers = ['app_id', 'chart', 'date', 'country', 'rank']
    out_filename = out_base.format('RANKINGS_IPHONE')
    with gzip.open(out_filename,'wt',compress) as out_file:
        csv_writer = csv.writer(out_file)
        csv_writer.writerow(headers)
        for json in iter_json_gzip(file_in):
            tree = lxml.html.fromstring(json['html'])
            app_ids = tree.xpath("//span[@style='display:none']")
            chart = ['free', 'paid', 'grossing']
            for i,app in enumerate(app_ids):
                app_info = [app.text_content(), chart[i%3], json['date'], 'United States', int(((i/3)+1))]
                csv_writer.writerow(app_info)
    return out_filename

In [9]:
df_debug = None
if DEBUG:
    df_debug = read_csv(RANKINGS_IPHONE(RAW_FILE_IPHONE,OUT_BASE,COMPRESS_LEVEL),compression='gzip',header=0)
df_debug

           app_id     chart        date        country  rank
0       826459257      free  2014-03-01  United States     1
1       503190232      paid  2014-03-01  United States     1
2       529479190  grossing  2014-03-01  United States     1
3       808176012      free  2014-03-01  United States     2
4       479516143      paid  2014-03-01  United States     2
5       553834731  grossing  2014-03-01  United States     2
6       766894692      free  2014-03-01  United States     3
7       623592465      paid  2014-03-01  United States     3
8       667728512  grossing  2014-03-01  United States     3
9       825289439      free  2014-03-01  United States     4
10      791341471      paid  2014-03-01  United States     4
11      284035177  grossing  2014-03-01  United States     4
12      811035387      free  2014-03-01  United States     5
13      634235735      paid  2014-03-01  United States     5
14      493619333  grossing  2014-03-01  United States     5
15      816765176      free  2014-03-01  United States     6
16      525818839      paid  2014-03-01  United States     6
17      538212549  grossing  2014-03-01  United States     6
18      819754949      free  2014-03-01  United States     7
19      667362389      paid  2014-03-01  United States     7
20      608206510  grossing  2014-03-01  United States     7
21      820625850      free  2014-03-01  United States     8
22      573116090      paid  2014-03-01  United States     8
23      468327549  grossing  2014-03-01  United States     8
24      447188370      free  2014-03-01  United States     9
25      779157948      paid  2014-03-01  United States     9
26      506627515  grossing  2014-03-01  United States     9
27      389801252      free  2014-03-01  United States    10
28      492367820      paid  2014-03-01  United States    10
29      563474464  grossing  2014-03-01  United States    10
...           ...       ...         ...            ...   ...
545970  931199028      free  2015-02-27  United States   491
545971  916130071      paid  2015-02-27  United States   491
545972  955222912  grossing  2015-02-27  United States   491
545973  367623543      free  2015-02-27  United States   492
545974  317809458      paid  2015-02-27  United States   492
545975  567767430  grossing  2015-02-27  United States   492
545976  635150066      free  2015-02-27  United States   493
545977  570306657      paid  2015-02-27  United States   493
545978  472006138  grossing  2015-02-27  United States   493
545979  942443178      free  2015-02-27  United States   494
545980  407838198      paid  2015-02-27  United States   494
545981  568556189  grossing  2015-02-27  United States   494
545982  749073889      free  2015-02-27  United States   495
545983  421894356      paid  2015-02-27  United States   495
545984  920482331  grossing  2015-02-27  United States   495
545985  472014516      free  2015-02-27  United States   496
545986  697927927      paid  2015-02-27  United States   496
545987  337021781  grossing  2015-02-27  United States   496
545988  804641004      free  2015-02-27  United States   497
545989  775888026      paid  2015-02-27  United States   497
545990  424606644  grossing  2015-02-27  United States   497
545991  550806860      free  2015-02-27  United States   498
545992  382991304      paid  2015-02-27  United States   498
545993  526713081  grossing  2015-02-27  United States   498
545994  633495655      free  2015-02-27  United States   499
545995  288419283      paid  2015-02-27  United States   499
545996  827743035  grossing  2015-02-27  United States   499
545997  312325565      free  2015-02-27  United States   500
545998  436111378      paid  2015-02-27  United States   500
545999  660333908  grossing  2015-02-27  United States   500

[546000 rows x 5 columns]

# RANKINGS_GOOGLE

In [10]:
@require(iter_json_gzip,'ujson','gzip','csv','lxml.html')
def RANKINGS_GOOGLE(file_in,out_base,compress=1):
    headers = ['app_id', 'chart', 'date', 'country', 'rank']
    out_filename = out_base.format('RANKINGS_GOOGLE')
    with gzip.open(out_filename,'wt',compress) as out_file:
        csv_writer = csv.writer(out_file)
        csv_writer.writerow(headers)
        for json in iter_json_gzip(file_in):
            tree = lxml.html.fromstring(json['html'])
            app_ids = tree.xpath("//span[@style='display:none']")
            chart = ['free', 'paid', 'grossing', 'new_free', 'new_paid']
            for i,app in enumerate(app_ids):
                app_info = [app.text_content(), chart[i%5], json['date'], 'United States', int(((i/5)+1))]
                csv_writer.writerow(app_info)
    return out_filename

In [11]:
df_debug = None
if DEBUG:
    df_debug = read_csv(RANKINGS_GOOGLE(RAW_FILE_GOOGLE,OUT_BASE,COMPRESS_LEVEL),compression='gzip',header=0)
df_debug

,app_id,chart,date,country,rank
0,com.facebook.katana,free,2014-03-01,United States,1
1,com.mojang.minecraftpe,paid,2014-03-01,United States,1
2,com.supercell.clashofclans,grossing,2014-03-01,United States,1
3,it.junglestudios.splashyfish,new_free,2014-03-01,United States,1
4,com.FireproofStudios.TheRoom2,new_paid,2014-03-01,United States,1
5,com.pandora.android,free,2014-03-01,United States,2
6,com.touchtype.swiftkey,paid,2014-03-01,United States,2
7,com.king.candycrushsaga,grossing,2014-03-01,United States,2
8,com.square_enix.android_googleplay.deadmanscro...,new_free,2014-03-01,United States,2
9,com.mtvn.sbmigoogleplay,new_paid,2014-03-01,United States,2
10,com.facebook.orca,free,2014-03-01,United States,3
11,com.keramidas.TitaniumBackupPro,paid,2014-03-01,United States,3
12,com.king.farmheroessaga,grossing,2014-03-01,United States,3
13,com.lego.city.my_city,new_free,2014-03-01,United States,3
14,com.tocaboca.tocalab,new_paid,2014-03-01,United States,3
15,com.instagram.android,free,2014-03-01,United States,4
16,com.teslacoilsw.launcher.prime,paid,2014-03-01,United States,4
17,com.supercell.hayday,grossing,2014-03-01,United States,4
18,com.magicyang.doodle,new_free,2014-03-01,United States,4
19,com.dotemu.rtype2,new_paid,2014-03-01,United States,4
20,com.king.candycrushsaga,free,2014-03-01,United States,5
21,com.maxmpz.audioplayer.unlock,paid,2014-03-01,United States,5
22,com.king.petrescuesaga,grossing,2014-03-01,United States,5
23,com.turborilla.MadSkillsMotocross2,new_free,2014-03-01,United States,5
24,com.marvel.runjumpsmash_goo,new_paid,2014-03-01,United States,5
25,com.netflix.mediaclient,free,2014-03-01,United States,6
26,com.foxfi.key,paid,2014-03-01,United States,6
27,com.igg.castleclash,grossing,2014-03-01,United States,6
28,com.xtpl.kingsAndCannon,new_free,2014-03-01,United States,6
29,net.broapp.app,new_paid,2014-03-01,United States,6
...,...,...,...,...,...
908695,com.prgames.texasholdem.livepoker,free,2014-06-09,United States,495
908696,com.johnemulators.johngbc,paid,2014-06-09,United States,495
908697,com.gameloft.android.ANMP.GloftGGHM,grossing,2014-06-09,United States,495
908698,com.vg.PoliceBoatSimulator,new_free,2014-06-09,United States,495
908699,air.com.dmg.medmed,new_paid,2014-06-09,United States,495
908700,com.stylem.wallpapers,free,2014-06-09,United States,496
908701,com.realarcade.CL4,paid,2014-06-09,United States,496
908702,com.zentertain.slotsvegas,grossing,2014-06-09,United States,496
908703,com.anall.wp8.theme,new_free,2014-06-09,United States,496
908704,air.com.differencegames.aljelementalguardians,new_paid,2014-06-09,United States,496
908705,com.pixlr.express,free,2014-06-09,United States,497
908706,com.mylegalheat.legalheat,paid,2014-06-09,United States,497
908707,kr.co.feverstudio.apps.everytown,grossing,2014-06-09,United States,497
908708,com.slushpupie.deskclock.m200,new_free,2014-06-09,United States,497
908709,next.launcher.tapanilab.theme.glaslightbluedeluxe,new_paid,2014-06-09,United States,497
908710,com.repostwhiz,free,2014-06-09,United States,498
908711,uk.co.neilandtheresa.NewVignette,paid,2014-06-09,United States,498
908712,com.gamevil.elements,grossing,2014-06-09,United States,498
908713,com.threeaplay.slotskingarther,new_free,2014-06-09,United States,498
908714,com.smurfinc.LauncPadPro,new_paid,2014-06-09,United States,498
908715,ppl.unity.JuiceCubesBeta,free,2014-06-09,United States,499
908716,com.hp.pregnancy,paid,2014-06-09,United States,499
908717,com.sixwaves.wonderlandepic,grossing,2014-06-09,United States,499
908718,com.TrudyHerkenratt.PhotoEditorCutPaste,new_free,2014-06-09,United States,499
908719,com.bigfish.flatty,new_paid,2014-06-09,United States,499
908720,com.calfordcn.gu,free,2014-06-09,United States,500
908721,com.wildtangent.polarbowleradventure,paid,2014-06-09,United States,500
908722,com.zynga.bubblesafari.ent,grossing,2014-06-09,United States,500
908723,tools.browser.webbrowser,new_free,2014-06-09,United States,500
908724,com.wallpaper.livewallpaper.AquariumLiveWallpa...,new_paid,2014-06-09,United States,500

# RANKINGS_IPAD

In [12]:
@require(iter_json_gzip,'ujson','gzip','csv','lxml.html')
def RANKINGS_IPAD(file_in,out_base,compress=1):
    headers = ['app_id', 'chart', 'date', 'country', 'rank']
    out_filename = out_base.format('RANKINGS_IPAD')
    with gzip.open(out_filename,'wt',compress) as out_file:
        csv_writer = csv.writer(out_file)
        csv_writer.writerow(headers)
        for json in iter_json_gzip(file_in):
            tree = lxml.html.fromstring(json['html'])
            app_ids = tree.xpath("//span[@style='display:none']")
            chart = ['free', 'paid', 'grossing']
            for i,app in enumerate(app_ids):
                app_info = [app.text_content(), chart[i%3], json['date'], 'United States', int(((i/3)+1))]
                csv_writer.writerow(app_info)
    return out_filename

In [13]:
df_debug = None
if DEBUG:
    print(type(RANKINGS_IPAD(RAW_FILE_IPAD,OUT_BASE,COMPRESS_LEVEL)))
    df_debug = read_csv(RANKINGS_IPAD(RAW_FILE_IPAD,OUT_BASE,COMPRESS_LEVEL),compression='gzip',header=0)
df_debug

<class 'str'>

           app_id     chart        date        country  rank
0       766894692      free  2014-03-01  United States     1
1       479516143      paid  2014-03-01  United States     1
2       529479190  grossing  2014-03-01  United States     1
3       826459257      free  2014-03-01  United States     2
4       667362389      paid  2014-03-01  United States     2
5       553834731  grossing  2014-03-01  United States     2
6       808176012      free  2014-03-01  United States     3
7       791341471      paid  2014-03-01  United States     3
8       667728512  grossing  2014-03-01  United States     3
9       808032599      free  2014-03-01  United States     4
10      808108897      paid  2014-03-01  United States     4
11      538212549  grossing  2014-03-01  United States     4
12      811035387      free  2014-03-01  United States     5
13      634235735      paid  2014-03-01  United States     5
14      506627515  grossing  2014-03-01  United States     5
15      608206510      free  2014-03-01  United States     6
16      622613679      paid  2014-03-01  United States     6
17      608206510  grossing  2014-03-01  United States     6
18      794524208      free  2014-03-01  United States     7
19      552039496      paid  2014-03-01  United States     7
20      485126024  grossing  2014-03-01  United States     7
21      363590051      free  2014-03-01  United States     8
22      768592901      paid  2014-03-01  United States     8
23      468327549  grossing  2014-03-01  United States     8
24      816765176      free  2014-03-01  United States     9
25      640111933      paid  2014-03-01  United States     9
26      493619333  grossing  2014-03-01  United States     9
27      544007664      free  2014-03-01  United States    10
28      576836614      paid  2014-03-01  United States    10
29      594843575  grossing  2014-03-01  United States    10
...           ...       ...         ...            ...   ...
348270  357066198      free  2014-10-25  United States   191
348271  495716481      paid  2014-10-25  United States   191
348272  868692227  grossing  2014-10-25  United States   191
348273  469231420      free  2014-10-25  United States   192
348274  549592189      paid  2014-10-25  United States   192
348275  606944207  grossing  2014-10-25  United States   192
348276  576731399      free  2014-10-25  United States   193
348277  501220013      paid  2014-10-25  United States   193
348278  555150599  grossing  2014-10-25  United States   193
348279  421998342      free  2014-10-25  United States   194
348280  869329921      paid  2014-10-25  United States   194
348281  643798619  grossing  2014-10-25  United States   194
348282  727420266      free  2014-10-25  United States   195
348283  378326916      paid  2014-10-25  United States   195
348284  703261181  grossing  2014-10-25  United States   195
348285  572537866      free  2014-10-25  United States   196
348286  399650655      paid  2014-10-25  United States   196
348287  401284198  grossing  2014-10-25  United States   196
348288  628677149      free  2014-10-25  United States   197
348289  515884174      paid  2014-10-25  United States   197
348290  537263603  grossing  2014-10-25  United States   197
348291  426170776      free  2014-10-25  United States   198
348292  780585714      paid  2014-10-25  United States   198
348293  690852527  grossing  2014-10-25  United States   198
348294  841069888      free  2014-10-25  United States   199
348295  594704446      paid  2014-10-25  United States   199
348296  414664715  grossing  2014-10-25  United States   199
348297  575658129      free  2014-10-25  United States   200
348298  540442762      paid  2014-10-25  United States   200
348299  593448569  grossing  2014-10-25  United States   200

[348300 rows x 5 columns]

# APPANNIEHISTORICALEVENTS

Make sure that date is of the format `2014-03-01`. See this [Google Notebook](http://nbviewer.ipython.org/github/mobileinnovationgroup/data_requests/blob/master/main/Google%20Data%20Request.ipynb) for examples of how to do this conversion correctly.

In [14]:
@require(iter_json_gzip,'ujson','gzip','csv','datetime')
def APPANNIEHISTORICALEVENTS(file_in,out_base,compress=1):
    headers = ['event_type', 'app_id', 'version', 'date']
    out_filename_ios = out_base.format('APPANNIEHISTORICALEVENTS_IOS')
    out_filename_google = out_base.format('APPANNIEHISTORICALEVENTS_GOOGLE')
    with gzip.open(out_filename_ios,'wt',compress) as out_file_ios:
        with gzip.open(out_filename_google,'wt',compress) as out_file_google:
            csv_writer_ios = csv.writer(out_file_ios)
            csv_writer_google = csv.writer(out_file_google)
            csv_writer_ios.writerow(headers)
            csv_writer_google.writerow(headers)
            for json in iter_json_gzip(file_in):
                if 'version' in json.keys():   #some data entries do not have the version data
                    version = json['version']
                else:
                    version = None
                data = [json['event_type'], json['app_id'], version, json['date']]
                if json['store'] == 'ios':
                    csv_writer_ios.writerow(data)
                else:
                    csv_writer_google.writerow(data)
    return [out_filename_ios, out_filename_google]

In [15]:
df_debug = None
if DEBUG:
    csvs = APPANNIEHISTORICALEVENTS(RAW_FILE_HISTORICALEVENTS,OUT_BASE,COMPRESS_LEVEL)
    df_debug_google = read_csv(csvs[1],compression='gzip',header=0)
    df_debug_ios = read_csv(csvs[0],compression='gzip',header=0)
df_debug_ios

          event_type     app_id                       version        date
0     version_change  281704574  4.1.1 (iphone os 3.0 tested)  2010-02-11
1    initial_release  362348516                           NaN  2010-03-31
2     version_change  281704574  4.1.2 (iphone os 3.0 tested)  2010-02-16
3     version_change  362348516                           1.1  2010-04-28
4    initial_release  520777858                           NaN  2012-05-15
5    initial_release  717142133                           NaN  2013-10-17
6     version_change  281704574                         4.2.1  2010-03-10
7     version_change  362348516                           1.2  2010-06-03
8     version_change  520777858                          1.02  2012-05-23
9     version_change  362348516                           1.3  2010-07-17
10    version_change  281704574                         4.2.2  2010-04-06
11    version_change  520777858                          1.03  2012-06-26
12    version_change  281704574                         4.3.1  2010-04-21
13    version_change  520777858                          1.04  2012-07-10
14    version_change  281704574                         4.3.2  2010-05-15
15    version_change  520777858                          1.05  2012-09-18
16    version_change  362348516                           1.4  2010-08-06
17    version_change  520777858                         1.051  2012-09-27
18    version_change  362348516                           2.0  2010-12-22
19    version_change  281704574                         4.3.3  2010-07-03
20    version_change  520777858                         1.052  2012-10-30
21    version_change  362348516                           2.1  2011-03-03
22    version_change  281704574                         4.3.4  2010-08-09
23    version_change  520777858                           1.1  2012-12-14
24    version_change  362348516                           2.2  2011-03-26
25    version_change  281704574                         4.3.5  2010-08-17
26    version_change  520777858                         1.101  2013-01-23
27    version_change  362348516                           2.3  2011-07-19
28    version_change  520777858                         1.150  2013-03-13
29    version_change  362348516                           2.4  2011-08-20
..               ...        ...                           ...         ...
355   version_change  281913144                         1.2.5  2010-04-09
356   version_change  281913144                         1.2.6  2010-05-12
357   version_change  281913144                         2.0.1  2010-10-20
358   version_change  281913144                         2.1.0  2011-04-22
359   version_change  281913144                         2.1.1  2011-06-15
360   version_change  281913144                         2.1.2  2011-08-02
361   version_change  281913144                         3.0.1  2011-10-22
362   version_change  281913144                         3.0.2  2012-04-21
363   version_change  281913144                         3.0.3  2012-07-30
364   version_change  281913144                         3.0.4  2012-09-29
365   version_change  748095052                           1.2  2013-12-02
366  initial_release  748095052                           NaN  2013-12-02
367   version_change  281913144                         4.0.8  2013-08-07
368   version_change  281913144                        4.1.77  2014-01-22
369   version_change  748095052                           1.3  2013-12-12
370   version_change  748095052                           1.4  2014-01-02
371   version_change  748095052                           1.5  2014-01-24
372     price_change  748095052                           NaN  2014-04-25
373     price_change  748095052                           NaN  2014-04-27
374  initial_release  468993411                           NaN  2011-10-05
375   version_change  468993411                           1.1  2011-10-17
376   version_change  468993411                           1.2  2012-01-09
377   version_change  468993411                           1.3  2012-01-19
378   version_change  468993411                           1.4  2012-06-22
379   version_change  468993411                         1.4.1  2012-10-01
380   version_change  468993411                         1.4.2  2012-10-24
381   version_change  468993411                         1.4.3  2013-03-06
382   version_change  468993411                           2.0  2013-07-04
383   version_change  468993411                           2.1  2013-11-14
384   version_change  468993411                           2.2  2013-12-10

[385 rows x 4 columns]

In [16]:
df_debug_google

,event_type,app_id,version,date
0,version_change,com.gau.go.launcher.lwp.core,1.0,2014-03-28
1,initial_release,air.com.dpflashes.clearvision3,NaN,2014-01-17
2,version_change,com.azumio.instantheartrate.full,2.5.1,2012-01-17
3,initial_release,com.gau.go.launcher.lwp.core,NaN,2014-03-28
4,version_change,air.com.dpflashes.clearvision3,1.0.2,2014-01-18
5,version_change,com.azumio.instantheartrate.full,2.5.2,2012-01-20
6,version_change,air.com.dpflashes.clearvision3,1.0.3,2014-01-27
7,version_change,com.azumio.instantheartrate.full,2.5.3,2012-01-24
8,initial_release,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,NaN,2012-10-18
9,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.0.1,2012-10-26
10,initial_release,com.azumio.instantheartrate.full,NaN,2012-01-24
11,version_change,com.azumio.instantheartrate.full,2.5.4,2012-01-26
12,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.2.0,2012-11-29
13,version_change,com.azumio.instantheartrate.full,2.5.5,2012-03-02
14,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.2.1,2012-12-11
15,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.3.0,2013-03-11
16,version_change,com.azumio.instantheartrate.full,2.5.7,2012-03-12
17,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.4.0,2013-05-21
18,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.4.1,2013-07-16
19,price_change,com.azumio.instantheartrate.full,NaN,2012-09-11
20,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.4.3,2013-08-08
21,price_change,com.azumio.instantheartrate.full,NaN,2013-11-10
22,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.5.0,2013-08-27
23,price_change,com.azumio.instantheartrate.full,NaN,2013-11-11
24,version_change,com.azumio.instantheartrate.full,2.5.8,2014-01-25
25,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.5.1,2013-09-04
26,version_change,com.azumio.instantheartrate.full,2.5.10,2014-01-26
27,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.5.2,2013-10-24
28,version_change,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,1.5.3,2014-05-07
29,version_change,com.azumio.instantheartrate.full,2.5.12,2014-01-27
...,...,...,...,...
585,version_change,com.jb.gokeyboard,1.7.0,2012-08-21
586,version_change,com.jb.gokeyboard,1.7.1,2012-08-24
587,version_change,com.jb.gokeyboard,1.7.2,2012-08-31
588,version_change,com.jb.gokeyboard,1.7.3,2012-09-07
589,version_change,com.jb.gokeyboard,1.8.0,2012-09-14
590,version_change,com.jb.gokeyboard,1.9.0,2012-09-27
591,version_change,com.jb.gokeyboard,1.9.1,2012-10-12
592,version_change,com.jb.gokeyboard,1.9.2,2012-11-04
593,version_change,com.jb.gokeyboard,1.9.3,2012-11-09
594,version_change,com.jb.gokeyboard,1.9.4,2012-12-01
595,version_change,com.jb.gokeyboard,1.9.5,2012-12-29
596,version_change,com.jb.gokeyboard,1.9.6,2013-01-06
597,version_change,com.jb.gokeyboard,1.9.7,2013-01-17
598,version_change,com.jb.gokeyboard,1.9.8,2013-01-31
599,version_change,com.jb.gokeyboard,1.9.9,2013-02-23
600,version_change,com.jb.gokeyboard,1.9.10,2013-03-22
601,version_change,com.jb.gokeyboard,1.9.11,2013-10-21
602,version_change,com.jb.gokeyboard,1.9.12,2013-12-06
603,version_change,com.jb.gokeyboard,1.9.13,2014-01-02
604,version_change,com.jb.gokeyboard,1.9.15,2014-01-20
605,version_change,com.jb.gokeyboard,2.0,2014-02-21
606,version_change,com.jb.gokeyboard,2.03,2014-03-17
607,version_change,com.jb.gokeyboard,2.05,2014-03-24
608,version_change,com.jb.gokeyboard,2.06,2014-04-04
609,version_change,com.jb.gokeyboard,2.07,2014-04-25
610,version_change,com.jb.gokeyboard,2.08,2014-05-14
611,version_change,com.jb.gokeyboard,2.09,2014-05-31
612,version_change,com.jb.gokeyboard,2.10,2014-06-22
613,version_change,com.jb.gokeyboard,varies with device,2014-07-12
614,initial_release,com.nrthm.monstersuniversitycamera,NaN,2013-08-02

# APPANNIEHISTORICALRANKINGS

In [17]:
@require(iter_json_gzip,'ujson','gzip','csv','datetime')
def APPANNIEHISTORICALRANKINGS(file_in,out_base,compress=1):
    headers = ['category', 'country', 'app_id', 'rank', 'date']
    out_filename_ios = out_base.format('APPANNIEHISTORICALRANKINGS_IOS')
    out_filename_google = out_base.format('APPANNIEHISTORICALRANKINGS_GOOGLE')
    with gzip.open(out_filename_ios,'wt',compress) as out_file_ios:
        with gzip.open(out_filename_google,'wt',compress) as out_file_google:
            csv_writer_ios = csv.writer(out_file_ios)
            csv_writer_google = csv.writer(out_file_google)
            csv_writer_ios.writerow(headers)
            csv_writer_google.writerow(headers)
            for json in iter_json_gzip(file_in):
                data = [json['category'], json['country'], json['app_id'], json['rank'], json['date']]
                if json['store'] == 'ios':
                    csv_writer_ios.writerow(data)
                else:
                    csv_writer_google.writerow(data)
    return [out_filename_ios, out_filename_google]

In [18]:
df_debug = None
if DEBUG:
    csvs = APPANNIEHISTORICALRANKINGS(RAW_FILE_HISTORICALRANKINGS,OUT_BASE,COMPRESS_LEVEL)
    df_debug_google = read_csv(csvs[1],compression='gzip',header=0)
    df_debug_ios = read_csv(csvs[0],compression='gzip',header=0)
df_debug_ios

      category        country     app_id  rank        date
0      overall  united states  717142133   425  2013-10-17
1      overall  united states  717142133   233  2013-10-18
2      overall  united states  717142133   118  2013-10-19
3      overall  united states  717142133    81  2013-10-20
4      overall  united states  717142133   113  2013-10-21
5      overall  united states  717142133   150  2013-10-22
6      overall  united states  717142133   177  2013-10-23
7      overall  united states  717142133   244  2013-10-24
8      overall  united states  717142133   327  2013-10-25
9      overall  united states  717142133   321  2013-10-26
10     overall  united states  717142133   350  2013-10-27
11     overall  united states  717142133   481  2013-10-28
12     overall  united states  717142133   621  2013-10-29
13     overall  united states  717142133   750  2013-10-30
14     overall  united states  717142133   825  2013-10-31
15     overall  united states  717142133   644  2013-11-01
16     overall  united states  717142133   428  2013-11-02
17     overall  united states  717142133   412  2013-11-03
18     overall  united states  717142133   551  2013-11-04
19     overall  united states  717142133   625  2013-11-05
20     overall  united states  717142133   697  2013-11-06
21     overall  united states  717142133   718  2013-11-07
22     overall  united states  717142133   604  2013-11-08
23     overall  united states  717142133   826  2013-11-09
24     overall  united states  717142133  1132  2013-11-10
25     overall  united states  362348516   740  2010-04-01
26     overall  united states  717142133  1339  2013-11-11
27     overall  united states  362348516   361  2010-04-02
28       games  united states  717142133   118  2013-10-17
29     overall        armenia  520777858    32  2012-05-16
..         ...            ...        ...   ...         ...
427    overall  united states  362348516   533  2010-07-12
428    overall  united states  362348516   526  2010-07-13
429  education  united states  717142133   215  2013-12-14
430      games        armenia  520777858  1100  2013-08-04
431  education  united states  717142133   208  2013-12-15
432    overall  united states  362348516   502  2010-07-14
433  education  united states  717142133   227  2013-12-16
434    overall  united states  281704574   157  2010-05-20
435    overall  united states  281704574   159  2010-05-21
436    overall  united states  362348516   524  2010-07-15
437      games        armenia  520777858  1085  2013-08-05
438  education  united states  717142133   232  2013-12-17
439    overall  united states  281704574   173  2010-05-22
440    overall  united states  362348516   489  2010-07-16
441    overall  united states  362348516   498  2010-07-17
442      games        armenia  520777858  1183  2013-08-06
443      games        armenia  520777858  1143  2013-08-07
444      games        armenia  520777858  1238  2013-08-08
445      games        armenia  520777858   976  2013-08-09
446    overall  united states  362348516   497  2010-07-18
447    overall  united states  281704574   174  2010-05-23
448  education  united states  717142133   237  2013-12-18
449    overall  united states  281704574   172  2010-05-24
450      games        armenia  520777858  1214  2013-08-10
451    overall  united states  362348516   553  2010-07-19
452  education  united states  717142133   252  2013-12-19
453      games        armenia  520777858   234  2013-08-20
454    overall  united states  362348516   545  2010-07-20
455      games        armenia  520777858   940  2013-08-21
456  education  united states  717142133   232  2013-12-20

[457 rows x 5 columns]

In [19]:
df_debug_google

,category,country,app_id,rank,date
0,live wallpaper,united states,com.gau.go.launcher.lwp.core,383,2014-04-02
1,overall,united states,air.com.dpflashes.clearvision3,505,2014-02-01
2,live wallpaper,united states,com.gau.go.launcher.lwp.core,167,2014-04-03
3,live wallpaper,united states,com.gau.go.launcher.lwp.core,135,2014-04-04
4,live wallpaper,united states,com.gau.go.launcher.lwp.core,135,2014-04-05
5,overall,united states,air.com.dpflashes.clearvision3,468,2014-02-02
6,live wallpaper,united states,com.gau.go.launcher.lwp.core,76,2014-04-06
7,overall,united states,air.com.dpflashes.clearvision3,416,2014-02-03
8,live wallpaper,united states,com.gau.go.launcher.lwp.core,60,2014-04-07
9,overall,united states,air.com.dpflashes.clearvision3,375,2014-02-04
10,live wallpaper,united states,com.gau.go.launcher.lwp.core,53,2014-04-08
11,overall,united states,air.com.dpflashes.clearvision3,357,2014-02-05
12,live wallpaper,united states,com.gau.go.launcher.lwp.core,48,2014-04-09
13,live wallpaper,united states,com.gau.go.launcher.lwp.core,42,2014-04-10
14,overall,united states,air.com.dpflashes.clearvision3,357,2014-02-06
15,live wallpaper,united states,com.gau.go.launcher.lwp.core,38,2014-04-11
16,overall,united states,air.com.dpflashes.clearvision3,303,2014-02-07
17,live wallpaper,united states,com.gau.go.launcher.lwp.core,35,2014-04-12
18,live wallpaper,united states,com.gau.go.launcher.lwp.core,32,2014-04-13
19,overall,united states,air.com.dpflashes.clearvision3,278,2014-02-08
20,live wallpaper,united states,com.gau.go.launcher.lwp.core,30,2014-04-14
21,overall,united states,air.com.dpflashes.clearvision3,230,2014-02-09
22,overall,united states,air.com.dpflashes.clearvision3,196,2014-02-10
23,live wallpaper,united states,com.gau.go.launcher.lwp.core,30,2014-04-15
24,overall,united states,air.com.dpflashes.clearvision3,168,2014-02-11
25,overall,argentina,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,493,2012-12-10
26,live wallpaper,united states,com.gau.go.launcher.lwp.core,33,2014-04-16
27,overall,united states,air.com.dpflashes.clearvision3,144,2014-02-12
28,overall,argentina,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,465,2012-12-11
29,live wallpaper,united states,com.gau.go.launcher.lwp.core,33,2014-04-17
...,...,...,...,...,...
513,personalization,united states,com.gau.go.launcher.lwp.core,126,2014-05-22
514,games,united states,air.com.dpflashes.clearvision3,451,2014-05-05
515,personalization,united states,com.gau.go.launcher.lwp.core,131,2014-05-23
516,overall,argentina,com.azumio.instantheartrate.full,125,2012-04-28
517,games,united states,air.com.dpflashes.clearvision3,455,2014-05-06
518,games,united states,air.com.dpflashes.clearvision3,461,2014-05-07
519,personalization,united states,com.gau.go.launcher.lwp.core,135,2014-05-24
520,personalization,united states,com.gau.go.launcher.lwp.core,134,2014-05-25
521,games,united states,air.com.dpflashes.clearvision3,456,2014-05-08
522,overall,argentina,com.azumio.instantheartrate.full,131,2012-04-29
523,personalization,united states,com.gau.go.launcher.lwp.core,145,2014-05-26
524,games,argentina,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,220,2013-01-20
525,overall,argentina,com.azumio.instantheartrate.full,133,2012-04-30
526,games,united states,air.com.dpflashes.clearvision3,454,2014-05-09
527,overall,argentina,com.azumio.instantheartrate.full,136,2012-05-01
528,personalization,united states,com.gau.go.launcher.lwp.core,142,2014-05-27
529,games,argentina,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,206,2013-01-21
530,games,united states,air.com.dpflashes.clearvision3,455,2014-05-10
531,overall,argentina,com.azumio.instantheartrate.full,138,2012-05-02
532,personalization,united states,com.gau.go.launcher.lwp.core,141,2014-05-28
533,games,argentina,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,191,2013-01-22
534,games,united states,air.com.dpflashes.clearvision3,460,2014-05-11
535,overall,argentina,com.azumio.instantheartrate.full,142,2012-05-03
536,games,argentina,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,191,2013-01-23
537,games,united states,air.com.dpflashes.clearvision3,452,2014-05-12
538,overall,argentina,com.azumio.instantheartrate.full,142,2012-05-04
539,games,united states,air.com.dpflashes.clearvision3,456,2014-05-13
540,overall,argentina,com.azumio.instantheartrate.full,142,2012-05-05
541,games,argentina,com.mobage.ww.a956.MARVEL_Card_Battle_Heroes_A...,150,2013-01-24
542,games,united states,air.com.dpflashes.clearvision3,457,2014-05-14